### ISSUE TITLE
Error: This type server is not supported

### ISSUE THREAD

**Issue by dff1993** [hprose/hprose-typescript#13]
import { Context, NextInvokeHandler, Service, Client, ClientContext, ServiceContext } from '@hprose/rpc-core';

        const service = new Service();
        service.addFunction(hello);
        const server = net.createServer();
        service.bind(server);
        server.listen(8412);
        const client = new Client('tcp://127.0.0.1:8412');
        const proxy = await client.useServiceAsync();
        const result = await proxy.hello('world');
        server.close();

为什么会这样呢

**Comment by dff1993** [comment]
@andot

**Comment by andot** [comment]
服务器端需要：
```
import '@hprose/rpc-node';
```
HTML5客户端需要:
```
import '@hprose/rpc-html5';
```

`@hprose/rpc-core` 是不包含具体传输协议实现的。
