### ISSUE TITLE
请问在连接RPC服务器时，如何判断是否正确连接？

### ISSUE THREAD

**Issue by YuetTusi** [hprose/hprose-typescript#14]
比如创建一个RPC Client：

```js
let client = new Client('tcp4://127.0.0.1:41622/');
```
我如何判断这个client是否正确连接上了服务器？

有什么回调方法，或是错误捕获？

**Comment by andot** [comment]
只有调用的时候，才会开始连接，创建客户端时并不会进行连接。所以，最简单的方法是，你直接写一个用于测试连接的服务方法去调用一下就知道了。

**Comment by YuetTusi** [comment]
> 只有调用的时候，才会开始连接，创建客户端时并不会进行连接。所以，最简单的方法是，你直接写一个用于测试连接的服务方法去调用一下就知道了。

哦哦，那么可以设置连接的超时时间么？

**Comment by andot** [comment]
客户端有一个 timeout 属性。
