### ISSUE TITLE
How can I use hprose in Typescript project?

### ISSUE THREAD

**Issue by YuetTusi** [hprose/hprose-typescript#4]
I use yarn add @types/phrose

But I can't find declare files of hprose.

Any solutions?

**Comment by andot** [comment]
yarn add @hprose/rpc-html5

**Comment by andot** [comment]
如果用 node 服务器

yarn add @hprose/rpc-node

**Comment by andot** [comment]
还有各种插件，根据需要 add 就行了：

yarn add @hprose/rpc-plugin-circuitbreaker
yarn add @hprose/rpc-plugin-cluster
yarn add @hprose/rpc-plugin-limiter
yarn add @hprose/rpc-plugin-loadbalancer
yarn add @hprose/rpc-plugin-log
yarn add @hprose/rpc-plugin-oneway
yarn add @hprose/rpc-plugin-push
yarn add @hprose/rpc-plugin-reverse

还有 jsonrpc 编码器：

yarn add @hprose/rpc-codec-jsonrpc

如果在微信小程序里面用：

yarn add @hprose/rpc-wx

**Comment by andot** [comment]
包名在 README 里面都列出来了，可以参考。

**Comment by YuetTusi** [comment]
> 还有各种插件，根据需要 add 就行了：
> 
> yarn add @hprose/rpc-plugin-circuitbreaker
> yarn add @hprose/rpc-plugin-cluster
> yarn add @hprose/rpc-plugin-limiter
> yarn add @hprose/rpc-plugin-loadbalancer
> yarn add @hprose/rpc-plugin-log
> yarn add @hprose/rpc-plugin-oneway
> yarn add @hprose/rpc-plugin-push
> yarn add @hprose/rpc-plugin-reverse
> 
> 还有 jsonrpc 编码器：
> 
> yarn add @hprose/rpc-codec-jsonrpc
> 
> 如果在微信小程序里面用：
> 
> yarn add @hprose/rpc-wx

**Comment by YuetTusi** [comment]
> 如果用 node 服务器
> 
> yarn add @hprose/rpc-node

```js
async function test() {
    const client = new Client('tcp://127.0.0.1:3000/');
    const proxy = await client.useServiceAsync();
}
```
执行`useServiceAsync`方法报并不支持tcp协议，是哪里用错了么？
```txt
Uncaught (in promise) Error: The protocol "tcp:" is not supported.
```

**Comment by andot** [comment]
你没有导入 @hprose/rpc-node 这个包
