### ISSUE TITLE
使用hprose3.0报不支持tcp协议

### ISSUE THREAD

**Issue by YuetTusi** [hprose/hprose-typescript#5]
```js
import { Client } from '@hprose/rpc-core';
async function test() {
    const client = new Client('tcp://127.0.0.1:3000/');
    const proxy = await client.useServiceAsync(); 
}
```
执行`useServiceAsync`方法报并不支持tcp协议，是哪里用错了么？
```txt
Uncaught (in promise) Error: The protocol "tcp:" is not supported.
```

**Comment by YuetTusi** [comment]
请问hprose3.0没有文档么？

**Comment by andot** [comment]
@hprose/rpc-core 是不包含具体传输协议实现的。你如果要使用 tcp 客户端，要用 @hprose/rpc-node。如果是在网页中使用的话，要用 @hprose/rpc-html5，但是网页上不支持 tcp。网页中只支持 http 和 ws（包括 https 和 wss）

**Comment by andot** [comment]
hprose 3.0 的文档在这里：https://github.com/hprose/hprose/wiki
