### ISSUE TITLE
参照代码示例向客户端推送报找不到方法？

### ISSUE THREAD

**Issue by YuetTusi** [hprose/hprose-typescript#6]
我参照hprose-typescript中的用例，向本地客户端推送消息，报找不到方法：

```txt
UnhandledPromiseRejectionWarning: Error: Can't find this method >().
```

请问是不是少引了什么包？

**Comment by andot** [comment]
嗯，你服务器添加推送插件了吗？

**Comment by YuetTusi** [comment]
> 嗯，你服务器添加推送插件了吗？

添加了，请问代码示例中`MockServer`的用法是？在订阅和推送时都要使用`MockServer`开一个服务么？

**Comment by andot** [comment]
MockServer 只是用来测试的，没有用处。
